#!/bin/bash

BuildDir=_build

ConfigureOpts=(
    --prefix="$Prefix"
    --libdir="$LibDir"
    --mandir="$ManDir"
    --infodir="$InfoDir"
    --sysconfdir="$Etc"
    --buildtype=release
    --backend=ninja
)

pkg_del_cflags '-std=gnu17'

pkg_configure() {
    local d=$SrcDir/_tmp
    mkdir -pm 700 "$d"
    export TMPDIR=$d
    meson setup "${ConfigureOpts[@]}" "$BuildDir" "$OrigSrcDir" || return 1
}

pkg_make() {
    ninja -C "$BuildDir"
}

pkg_install() {
    DESTDIR="$DestDir" ninja -C "$BuildDir" install
}

pkg_distclean() {
    local dir=$BuildDir
    if [[ -d $dir ]]; then
        rm -rf "$dir"
    fi
}
