#!/bin/bash

PkgHome="https://gitlab.freedesktop.org/cairo/cairomm/-/tags"

ConfigureOpts+=(
    # Slackware
    -Dboost-shared=true # false, Use shared version of boost

    -Dbuild-documentation=false
    -Dbuild-examples=false
    -Dbuild-tests=false
)
