#!/bin/bash

PkgHome="https://www.cairographics.org/releases/?C=M;O=D"

ConfigureOpts+=(
    # Slackware
    -Dboost-shared=true # false, Use shared version of boost

    -Dbuild-documentation=false
    -Dbuild-examples=false
    -Dbuild-tests=false
)
