#!/bin/bash

ConfigureOpts+=(
    # Slackware
    -Dbash_completion=false
    -Dgtk_doc=true
    -Dman=true
)

pkg_post_install() {
    # Slackware
    # bash-completion is not available at build time, so install the file manually:
    pkg_install_mfd 644 bin/completion/dconf "$ShareDir2"/bash-completion/completions
}

pkg_read2var pkg_post_installpkg <<EOF
pkg_post_installpkg() {
    # Slackware
    # Reload messagebus service
    if [[ -x /etc/rc.d/rc.messagebus ]]; then
        sh /etc/rc.d/rc.messagebus reload &>/dev/null
    fi
    # Try to run these.  If they fail, no biggie.
    # chroot . /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/ &>/dev/null
    # chroot . /usr/bin/gio-querymodules "$LibDir"/gio/modules/ &>/dev/null
}
pkg_post_installpkg
EOF

