#!/bin/bash

PkgHome="https://git.kernel.org/pub/scm/utils/dtc/dtc.git"

# REQ BY: qemu

BuildSteps=("${BuildForPython[@]}")
[[ $BuildStep ]] && pkg_set_python "$BuildStep"

ConfigureOpts+=(
    -Dtests=false # true, Build tests
)

pkg_pre_configure() {
    if [[ $Version = "1.7.2" ]]; then
        pkg_patch_f3 dtc-1.7.2-glibc_fixes-1.patch 1 || return 1
    fi

    if (($(pkg_cmp_versions "$Version" "1.8") < 0)); then
        # #!/usr/bin/env python3
        # ->
        # #!python3.12
        pkg_create_orig setup.py
        sed -i -e "1s,.*,#!python$PythonV12," setup.py
    else
        # meson.build
        # py = py.find_installation(required: get_option('python'))
        # ->
        # py = py.find_installation('python3.12', required: get_option('python'))
        pkg_create_orig meson.build
        local s1='(py\.find_installation)\((.*)(required:.*)'
        local s2="\\1('python$PythonV12', \\3"
        sed -i -re "s|$s1|$s2|" meson.build
    fi
}

pkg_post_install() {
    # Slackware
    # del *.a
    find "$LibDir2" -type f -name '*.a' -delete
}
