#!/bin/bash

PkgHome="https://mirrors.edge.kernel.org/pub/software/utils/dtc/"

# REQ BY: qemu

BuildSteps=("${BuildForPython[@]}")
[[ $BuildStep ]] && pkg_set_python "$BuildStep"

ConfigureOpts+=(
    -Dstatic-build=false # false, Build static binaries
        # doesn't work
    -Dtests=false # true, Build tests
)

pkg_pre_configure() {
    if [[ $Version = "1.7.2" ]]; then
        pkg_patch_f3 dtc-1.7.2-glibc_fixes-1.patch 1 || return 1
    fi

    # #!/usr/bin/env python3
    # ->
    # #!$Python
    pkg_create_orig setup.py
    sed -i -e "1s,.*,#!$Python," setup.py
}

pkg_post_install() {
    # del *.a
    find "$LibDir2" -type f -name '*.a' -delete
}
