#!/bin/bash

PkgHome="https://github.com/elogind/elogind/tags"

ConfigureOpts+=(
    # Slackware
    --libdir=/"$LibName"
    --libexecdir=/"$LibName"/elogind
    -Dpkgconfiglibdir="$LibDir"/pkgconfig
    -Dpamlibdir=/"$LibName"/security
    -Dudevrulesdir=/lib/udev/rules.d
    -Ddocdir="$DocDir"
    -Dhtmldir="$DocDir"/html
    # -Dmandir="$ManDir" # --mandir
    -Dman=enabled
    -Dhtml=disabled
    -Dbashcompletiondir="$ShareDir"/bash-completion/completions
    -Dnobody-user=nobody
    -Dnobody-group=nogroup
    -Dpam=enabled
    -Dpamconfdir=/etc/pam.d
    -Dacl=enabled
    -Dsmack=false
    -Duserdb=true
    -Dutmp=true
    -Ddefault-hierarchy=legacy
    -Dcgroup-controller=elogind
    -Dhalt-path=/sbin/halt
    -Dpoweroff-path=/sbin/poweroff
    -Dreboot-path=/sbin/reboot
    -Ddefault-kill-user-processes=false
    -Dmode=release
)

pkg_pre_configure() {
    # Slackware
    # Once upon a time we were encouraged to go against long-standing UNIX
    # traditions and use 99:99 for nobody:nogroup.
    # This may have been a bad idea.
    # But since to change this we'll have to dig through the system and make
    # sure that nothing hardcodes 99:99, we'll leave it as-is for now.
    # It's more than likely on the TODO list to change these back to
    # 65534:65534, however.
    # Meanwhile we'll at least change this from a sed to a patch.
    # Always hated sed in these situations because the underlying code can change
    # but sed will still happily scribble all over everything.
    pkg_patch_f3 elogind.nobody.nogroup.99.99.diff 1 || return 1
    #
    pkg_patch_f3 elogind-remove-orphaned-session-cgroups.patch 1 || return 1
    #
    # File "../man/elogind.syntax.xml", line 5
    # lxml.etree.XMLSyntaxError: Entity 'entities' not defined, line 5, column 11
    # tools/xml_helper.py
    # -_parser = tree.XMLParser()
    # +_parser = tree.XMLParser(resolve_entities=True)
    local f1=tools/xml_helper.py
    local s1='_parser = tree.XMLParser()'
    local s2='_parser = tree.XMLParser(resolve_entities=True)'
    sed -i -e "s,$s1,$s2," "$f1"
}

pkg_post_install() {
    # Slackware
    # Create symlinks for elogind binaries to /bin/:
    ls -d "$Prefix2"/bin/{elogind-inhibit,loginctl,userdbctl,varlinkctl} | pkg_ln_d "$DestDir"/bin
    # Remove references to systemd tools:
    sed -i '/systemd-analyze cat-config/d' "$Etc2"/elogind/*.conf
    # Create /etc/userdb directory:
    mkdir -p "$Etc2"/userdb
    # Add an rc script:
    pkg_install_mfd 755 "$SupportDir"/rc.elogind "$Etc2"/rc.d
    sed -i -e "s/@LIBDIRSUFFIX@/$LibSuffix/g" "$Etc2"/rc.d/rc.elogind
    # Create supported dirs in /etc/elogind/ (local config)
    mkdir -p "$Etc2"/elogind/{logind.conf.d,sleep.conf.d}
    # Add login1 policy file that allows users in the 'power' group
    # to shutdown/reboot the computer:
    pkg_install_mff 644 "$SupportDir"/10-enable-elogind-power.rules \
        "$ShareDir2"/polkit-1/rules.d/10-enable-session-power.rules
    # We don't need the hidden files to make inferior package managers keep dirs:
    find "$DestDir" -type f -name ".keep_dir" -delete
}

pkg_read2var pkg_post_installpkg <<EOF
pkg_post_installpkg() {
    # Slackware
    # Reload elogind-daemon:
    if pgrep -f elogind-daemon &>/dev/null; then
        pkill -HUP -f elogind-daemon
    fi
}
pkg_post_installpkg
EOF
