#!/bin/bash

# REQ: python-pillow, pygobject, tpm2-tss, libsmbios
# REQ: kernel (msr, platform-integrity, EFIVAR_FS)
# v2.0.6: pango<1.56.2
# https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface

# daemon: /usr/libexec/fwupd/fwupd
# client: /usr/bin/fwupdmgr [get-devices | get-updates | update | refresh]

PkgHome="https://github.com/fwupd/fwupd"

ConfigureOpts+=(
    # Slackware
    -Db_lto=true
    -Dbuild=all
    #-Dconsolekit=disabled # deprecated
    #-Delogind=disabled # deprecated
    -Dfirmware-packager=true
    -Dgcab:docs=false
    #-Dhsi=enabled # deprecated, Host Security Information
    -Dlvfs=true # install LVFS remotes
    -Dman=true
    -Dpassim=disabled # Passim support
    #-Dplugin_amdgpu=disabled
    #-Dplugin_redfish=disabled # deprecated, Redfish support
    #-Dplugin_uefi_capsule=enabled # deprecated
    #-Dsupported_build=enabled # deprecated, distribution package with upstream support
    #-Dsystemd=disabled # deprecated

    -Dtests=false
    -Ddocs=disabled

    -Dplugin_modem_manager=disabled # deprecated, ModemManager support
        # plugins/modem-manager/fu-mm-device.c:1592:22: warning: nested extern declaration of ‘fu_mm_device_mbim_switch_to_edl’ [-Wnested-externs]
)

# 2.0.7
# meson.build:1:0: ERROR: Unknown options: "plugin_amdgpu, plugin_logitech_bulkcontroller"
if (($(pkg_cmp_versions "$Version" "2.0.7") < 0)); then
    ConfigureOpts+=(
        # Slackware
        -Dplugin_amdgpu=disabled

        -Dplugin_logitech_bulkcontroller=disabled # Logitech bulk controller support
            # This plugin can upgrade the firmware on Logitech Video Collaboration products
            # (Rally Bar and RallyBar Mini), using USB bulk transfer.
            # FAILED: plugins/logitech-bulkcontroller/libfu_plugin_logitech_bulkcontroller.a.p/antiflicker.pb-c.c plugins/logitech-bulkcontroller/libfu_plugin_logitech_bulkcontroller.a.p/antiflicker.pb-c.h 
            # /usr/bin/protoc --proto_path=../plugins/logitech-bulkcontroller/proto --c_out=plugins/logitech-bulkcontroller/libfu_plugin_logitech_bulkcontroller.a.p ../plugins/logitech-bulkcontroller/proto/antiflicker.proto
            # protoc-gen-c: symbol lookup error: protoc-gen-c: undefined symbol: _ZN6google8protobuf2io7Printer9PrintImplESt17basic_string_viewIcSt11char_traitsIcEEN4absl12lts_202407224SpanIKNSt7__cxx1112basic_stringIcS5_SaIcEEEEENS2_12PrintOptionsE
            # --c_out: protoc-gen-c: Plugin failed with status code 127.
    )
fi

pkg_post_install() {
    local dir fn

    # Slackware
    # fix permissions on rules.d
    local dir=$ShareDir2/polkit-1/rules.d
    chown polkitd:root "$dir"
    chmod 0700 "$dir"
    # dbxtool -> fwupd-dbxtool
    dir=$Prefix2/bin
    mv "$dir"/dbxtool "$dir"/$Name-dbxtool
    dir=$ManDir2/man1
    mv "$dir"/dbxtool.1 "$dir"/fwupd-dbxtool.1


    # v2.0.7
    # /usr/share/dbus-1/system-services/org.freedesktop.fwupd.service
    dir=$ShareDir2/dbus-1/system-services
    fn=org.freedesktop.fwupd.service
    if [[ ! -f $dir/$fn ]]; then
        pkg_install_mfd 644 "$SupportDir/$fn" "$dir"
    fi
}
