#!/bin/bash

# REQ: glad2 (python)

PkgHome="https://code.videolan.org/videolan/libplacebo"

ConfigureOpts+=(
    # Slackware
    -Ddemos=false # true, Enable building (and installing) the demo programs
    -Dglslang=enabled
    -Ddovi=disabled
    -Dlibdovi=disabled
    -Dd3d11=disabled
)

pkg_pre_configure() {
    if (($(pkg_cmp_versions "$Version" "7.351") < 0)); then
        # Slackware
        # Build against glslang 15:
        pkg_patch_f3 056b852018db04aa2ebc0982e27713afcea8106b.patch 1 || return 1
    fi
}
