#!/bin/bash

PkgHome=(
    "https://gitlab.freedesktop.org/pipewire/pipewire/-/tags"
    "$SlackwareMirrorUrl/l/pipewire/?C=M&O=D"
)

# REQ: rst2man (python docutils)
# subproject/wireplumber is fetched from
#   https://gitlab.freedesktop.org/pipewire/wireplumber.git

ConfigureOpts+=(
    # Slackware
    -Dudevrulesdir=/lib/udev/rules.d
    -Dman=enabled # disabled, Manual pages
    -Dffmpeg=enabled # disabled, Enable ffmpeg spa plugin integration
    -Dvulkan=enabled # disabled, Enable vulkan spa plugin integration
    # -Dpipewire-jack=enabled
    # -Djack-devel=true
    # -Dgsettings-pulse-schema=enabled # Install gsettings schema for pulseaudio', value: 'auto'
    -Dsession-managers=[] # [wireplumber], Session managers to build (can be [] for none or an absolute path)

    -Dexamples=disabled # enabled, Build examples
    -Dtests=disabled # enabled, Build tests
    -Dlibsystemd=disabled # Enable code that depends on libsystemd, =auto
    -Dlogind-provider=libelogind # ['libelogind', 'libsystemd'], =libsystemd, Provider for logind integration
)

if [[ $PULSE ]]; then
    # Slackware
    ConfigureOpts+=(-Dgsettings-pulse-schema=enabled)
else
    ConfigureOpts+=(-Dlibpulse=disabled -Dgsettings-pulse-schema=disabled)
fi
if [[ $JACK ]]; then
    # Slackware
    ConfigureOpts+=(-Dpipewire-jack=enabled -Djack-devel=true)
else
    ConfigureOpts+=(-Djack=disabled -Dpipewire-jack=disabled)
fi

pkg_post_install() {
    local dir

    # Slackware
    # Create system config file override directory:
    mkdir -p "$Etc2"/pipewire
    # Add configuation files:
    dir=$Etc2/xdg/autostart
    pkg_install_mfd 644 "$SupportDir"/pipewire.desktop "$dir"
    # Don't install this, pipewire-start makes it unnecessary:
    # pkg_install_mfd 644 "$SupportDir"/pipewire-pulse.desktop "$dir"
    dir=$Prefix2/sbin
    pkg_install_mfd 755 "$SupportDir"/pipewire-disable.sh "$dir"
    pkg_install_mfd 755 "$SupportDir"/pipewire-enable.sh "$dir"
    dir=$Etc2/profile.d
    # Don't start pipewire on the console by default.
    # If you want this, make the profile scripts executable.
    pkg_install_mfd 644 "$SupportDir"/pipewire.sh "$dir"
    pkg_install_mfd 644 "$SupportDir"/pipewire.csh "$dir"
    # pipewire-start
    pkg_install_mfd 755 "$SupportDir"/pipewire-start "$Prefix2"/bin
    # Add pipewire-jack libraries to the ld.so path:
    if [[ $JACK ]]; then
        dir=$Etc2/ld.so.conf.d
        pkg_install_mfd 644 "$SupportDir"/pipewire-jack-$LibName.conf "$dir"
    fi

    # rm -f "$Etc2/xdg/autostart"/*media-session*
}

pkg_read2var pkg_post_installpkg <<EOF
pkg_post_installpkg() {
    # Slackware
    # Toss redundant sample files:
    local dir=etc/xdg/autostart
    local file
    for file in pipewire.desktop pipewire-pulse.desktop; do
        cmp -s "\$dir/\$file" "\$dir/\$file.sample" && rm -f "\$dir/\$file.sample"
    done
    # Disable pulseaudio.desktop:
    file=etc/xdg/autostart/pulseaudio.desktop
    if [[ -r \$file ]]; then
        if ! grep -q "^Hidden=true$" "\$file" ; then
            echo "Hidden=true" >> "\$file"
        fi
    fi
    # Pipewire is now the default multimedia server, so if we see pulseaudio
    # running let's kill it so that it doesn't interfere:
    killall --ns \$\$ /usr/bin/pulseaudio &>/dev/null
}
pkg_post_installpkg
EOF
