#!/bin/bash

PkgHome=(
    "https://gitlab.freedesktop.org/pipewire/pipewire/-/tags"
    "$SlackwareMirrorUrl/l/pipewire/?C=M&O=D"
)

# REQ: rst2man (python docutils)
# subproject/wireplumber is fetched from
#   https://gitlab.freedesktop.org/pipewire/wireplumber.git

ConfigureOpts+=(
    # Slackware
    -Dudevrulesdir=/lib/udev/rules.d
    -Dman=enabled # disabled, Manual pages
    -Dffmpeg=enabled # disabled, Enable ffmpeg spa plugin integration
    -Dvulkan=enabled # disabled, Enable vulkan spa plugin integration
    # -Dpipewire-jack=enabled
    # -Djack-devel=true
    # -Dgsettings-pulse-schema=enabled # Install gsettings schema for pulseaudio', value: 'auto'
    -Dsession-managers=[] # [wireplumber], Session managers to build (can be [] for none or an absolute path)

    -Dexamples=disabled # enabled, Build examples
    -Dtests=disabled # enabled, Build tests
)

if [[ $PULSE ]]; then
    # Slackware
    ConfigureOpts+=(-Dgsettings-pulse-schema=enabled)
else
    ConfigureOpts+=(-Dlibpulse=disabled -Dgsettings-pulse-schema=disabled)
fi
if [[ $JACK ]]; then
    # Slackware
    ConfigureOpts+=(-Dpipewire-jack=enabled -Djack-devel=true)
else
    ConfigureOpts+=(-Djack=disabled -Dpipewire-jack=disabled)
fi

if (($(pkg_cmp_versions "$Version" "1.6") < 0)); then
    ConfigureOpts+=(
        -Dsystemd=disabled
    )
else
    ConfigureOpts+=(
        -Dlibsystemd=disabled # Enable code that depends on libsystemd, =auto
        -Dlogind-provider=libelogind # ['libelogind', 'libsystemd'], =libsystemd, Provider for logind integration
    )
fi

pkg_post_install() {
    # Slackware
    # Create system config file override directory:
    mkdir -p "$Etc2/$Name"
    # Add sample configuation files:
    pkg_install_mfd 644 "$SupportDir"/*.desktop.sample "$Etc2/xdg/autostart"
    pkg_install_mfd 755 "$SupportDir"/pipewire-{enable,disable}.sh "$Prefix2/sbin"
    pkg_install_mfd 755 "$SupportDir"/pipewire.{sh,csh} "$Etc2/profile.d"

    rm -f "$Etc2/xdg/autostart"/*media-session*
}

pkg_read2var pkg_post_installpkg <<EOF
pkg_post_installpkg() {
    # Slackware
    # Toss redundant sample files:
    local d=etc/xdg/autostart
    local file
    for file in pipewire.desktop pipewire-pulse.desktop; do
        cmp -s "\$d/\$file" "\$d/\$file.sample" && rm -f "\$d/\$file.sample"
    done
}
pkg_post_installpkg
EOF
