#!/bin/bash

PkgHome="https://github.com/aristocratos/btop"

# CMake Error at /usr/share/cmake-4.0/Modules/CheckIPOSupported.cmake:84 (message):
#   IPO is not supported (check failed to compile).
UseClang=
