#!/bin/bash

PkgHome="https://github.com/knik0/faad2/tags"

pkg_post_install() {
    local f1=$OrigSrcDir/frontend/faad.man
    local f2=$ManDir2/man1/faad.1
    if [[ -f $f1 && ! -f $f2 ]]; then
        pkg_install_mff 644 "$f1" "$f2"
    fi
}
