#!/bin/bash

PkgHome="https://github.com/intel/media-driver"

# REQ: intel-gmmlib

# intel-media-24.2.5
# media_softlet/linux/common/os/xe/mos_bufmgr_xe.c:1037:52:
# error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
UseClang=
