#!/bin/bash

PkgHome="https://github.com/lensfun/lensfun"

BuildSteps=("${BuildForPython[@]}")
[[ $BuildStep ]] && pkg_set_python "$BuildStep"

ConfigureOpts+=(
    # Slackware
    -DBUILD_LENSTOOL=ON
    -DBUILD_FOR_SSE=ON
    -DBUILD_FOR_SSE2=ON
    -DBUILD_TESTS=OFF
    -DINSTALL_HELPER_SCRIPTS=ON

    -DPython3_EXECUTABLE="$Python"
)

pkg_post_install() {
    pkg_python_compileall "$PythonLibDir2"
}
