#!/bin/bash

PkgHome=(
    "https://aomedia.googlesource.com/aom/"
    "https://gitlab.com/webmproject/libaom/-/tags"
)

# REQ: nasm-2.x
# libheif REQ: /usr/lib64/libaom.a

ConfigureOpts+=(
    # Slackware
    -DENABLE_NASM=1
    -DENABLE_DOCS=0
    -DENABLE_TESTS=0

    -DCMAKE_INSTALL_LIBDIR="$LibName"
)
