#!/bin/bash

PkgHome="https://github.com/libjxl/libjxl/tags"

# 17 min

ConfigureOpts+=(
    # Slackware
    -DJPEGXL_BUNDLE_LIBPNG=OFF
    -DJPEGXL_ENABLE_BENCHMARK=OFF
    -DJPEGXL_ENABLE_EXAMPLES=OFF
    -DJPEGXL_ENABLE_FUZZERS=OFF
    -DJPEGXL_ENABLE_OPENEXR=OFF
    -DJPEGXL_ENABLE_PLUGINS=OFF
    -DJPEGXL_ENABLE_VIEWERS=OFF
    -DJPEGXL_FORCE_SYSTEM_BROTLI=ON
    -DJPEGXL_FORCE_SYSTEM_GTEST=ON
    -DJPEGXL_FORCE_SYSTEM_HWY=ON
    -DJPEGXL_INSTALL_JARDIR="/usr/share/java"
    -DBUILD_TESTING=OFF

    -DJPEGXL_STATIC=OFF
    -DJPEGXL_VERSION="$Version" # if .git/ not exist
)

pkg_pre_configure() {
    local i deps f2

    # download_github third_party/*
    deps=$OrigSrcDir/deps.sh
    if [[ -x $deps  ]]; then
        if pkg_create_orig "$deps"; then
            # THIRD_PARTY_LIBJPEG_TURBO
            # varname="${varname/[\/-]/_}"
            # varname="${varname//[\/-]/_}"
            sed -i -r -e 's,^( +)(varname="\$\{varname)/([^/].*),\1\2//\3,' "$deps"

            # exclude some libs
            for i in brotli highway zlib libpng; do
                sed -i -r -e 's,^( +)(download_github .*'"$i"')$,\1#\2,' "$deps"
            done
        fi
        # launch deps
        f2=$OrigSrcDir/third_party/skcms/skcms.h
        if [[ ! -f $f2 ]]; then
            "$deps"
        fi
    fi
}

pkg_post_install() {
    find "$LibDir2" -type f -name '*.a' -delete
}
