#!/bin/bash

PkgHome="https://github.com/mltframework/mlt/tags"

BuildSteps=("${BuildForPython[@]}")
[[ $BuildStep ]] && pkg_set_python "$BuildStep"

ConfigureOpts+=(
    # Slackware
    # -DMOD_QT=ON
    -DMOD_QT6=ON
    -DMOD_OPENCV=ON
    -DSWIG_PYTHON=ON
    -DMOD_JACKRACK=OFF
    -DMOD_RUBBERBAND=OFF
    # The Glaxnimate source ships embedded in the official MLT release tarball
    # (https://github.com/mltframework/mlt/releases). No separate fetch or
    # submodule handling is needed -- the upstream tree under
    # src/modules/glaxnimate/glaxnimate/ is already the exact version MLT expects.
    -DMOD_GLAXNIMATE_QT6=ON
    -DQT_VERSION_MAJOR=6
)

pkg_pre_configure() {
    # Slackware
    pkg_patch_f3 ffmpeg-9.patch 1 || return 1

    # find_package(Python3 REQUIRED COMPONENTS Interpreter Development)
    # ->
    # find_package(Python3 "3.12...3.12.13" REQUIRED COMPONENTS Interpreter Development)
    local f1=$OrigSrcDir/CMakeLists.txt
    pkg_create_orig "$f1"
    local s1='(find_package\(Python3).* (REQUIRED.*)'
    local s2='\1 "'"$PythonV12...$PythonV123"'" \2'
    sed -i -re "s,$s1,$s2," "$f1"

    # -libpostproc (ffmpeg-7.1)
    local f1=$OrigSrcDir/cmake/FindFFmpeg.cmake
    if pkg_create_orig "$f1"; then
        # find_component(POSTPROCESS libpostproc    postproc    libpostproc/postprocess.h)
        sed -i -re 's,^( *)(find_component\(POSTPROCESS .*),\1#\2,' "$f1"
    fi
}

pkg_post_install() {
    "$Python" -m compileall "$PythonPlatPrefix2" -d /
}
