#!/bin/bash

PkgHome="https://github.com/mltframework/mlt"

python=1

ConfigureOpts+=(
    #Slackware
    -DMOD_QT=ON
    -DMOD_QT6=ON
    -DMOD_JACKRACK=OFF
    -DMOD_RUBBERBAND=OFF
    -DMOD_GLXANIMATE=ON
    -DMOD_GLXANIMATE_QT6=ON

    #-DMOD_OPENCV=ON
)

if [[ $python ]]; then
    ConfigureOpts+=(-DSWIG_PYTHON=ON)
    pkg_set_python python3
fi

pkg_post_install() {
    if [[ $python ]]; then
        pkg_python_compileall "$LibDir2"
    fi
}
