#!/bin/bash

PkgHome="https://github.com/uclouvain/openjpeg"

ConfigureOpts+=(
    # Slackware
    -DOPENJPEG_INSTALL_LIB_DIR="$LibName"
    -DOPENJPEG_INSTALL_MAN_DIR=man
    -DOPENJPEG_INSTALL_DOC_DIR="doc/$FullName"
    -DOPENJPEG_INSTALL_SHARE_DIR="share/openjpeg"
    -DBUILD_JPWL=ON
    -DBUILD_MJ2=ON
    -DBUILD_JPIP=ON
    -DBUILD_JP3D=ON
    -DBUILD_STATIC_LIBS=OFF

    #-DBUILD_JAVA=False
    -DJAVA_SOURCE_VERSION="1.8"
    -DJAVA_TARGET_VERSION="1.8"

    -DBUILD_CODEC=ON
    -DBUILD_THIRDPARTY=ON
    -DBUILD_DOC=OFF
)
pkg_check=
