#!/bin/bash

PkgHome="https://gitlab.freedesktop.org/poppler/poppler"

ConfigureOpts+=(
    # Slackware
    #-DENABLE_QT5=ON
    #-DENABLE_XPDF_HEADERS=ON # not used by the project
    #-DENABLE_CMS=lcms2 # not used by the project
    #-DENABLE_LCMS=ON # Use LCMS for color management, ON
    #-DENABLE_DCTDECODER=libjpeg # Use libjpeg for DCT streams.
        # Default: libjpeg
        # Possible values: libjpeg, unmaintained, none. will use libjpeg if available or fail if not.
        # 'unmaintained' gives you the internal unmaintained decoder.
        # Use at your own risk. 'none' compiles no DCT decoder at all.
    #-DENABLE_GTK_DOC=ON
    #-DENABLE_LIBOPENJPEG=openjpeg2 # Use libopenjpeg for JPX streams.
        # Default: openjpeg2
        # Possible values: openjpeg2, unmaintained, none.
        # 'unmaintained' gives you the internal unmaintained decoder.
        # Use at your own risk.
        # 'none' compiles no JPX decoder at all.
    -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
        # poppler-config.h
        # UTF.h (inkscape)
    #-DENABLE_ZLIB=ON # not found

    #-DENABLE_SPLASH=ON
    #-DENABLE_BOOST=OFF

    -DBUILD_GTK_TESTS=OFF       # Whether to compile the GTK+ test programs
    -DBUILD_QT5_TESTS=OFF       # Whether to compile the Qt5 test programs
    -DBUILD_QT6_TESTS=OFF       # Whether to compile the Qt6 test programs
    -DBUILD_CPP_TESTS=OFF       # Whether to compile the CPP test programs
    -DBUILD_MANUAL_TESTS=OFF    # Whether to compile manual test programs
)
