#!/bin/bash

PkgHome="https://github.com/RawTherapee/RawTherapee/tags"

# REQ: libiptcdata

ConfigureOpts+=(
    -DBUILD_SHARED=ON
    -DLIBDIR="$LibDir"
    -DBUILD_SHARED_LIBS=ON
    -DWITH_SYSTEM_LIBRAW=ON # Build using system LibRaw library, OFF
)
