#!/bin/bash

PkgHome=(
    "https://github.com/facebook/zstd/tags"
    "$SlackwareMirrorUrl/l/zstd/?C=M&O=D"
)

SrcDir=$OrigSrcDir/build/cmake

ConfigureOpts+=(
    # Slackware
    -DZSTD_BUILD_STATIC=ON
    -DZSTD_PROGRAMS_LINK_SHARED=ON
    -DZSTD_LZ4_SUPPORT=ON
    -DZSTD_LZMA_SUPPORT=ON
    -DZSTD_ZLIB_SUPPORT=ON
)

pkg_post_make() {
    # Slackware
    # Compile and install pzstd:
    # zstd.dont.link.pzstd.to.static.libzstd.a.diff.gz
    local f1=$OrigSrcDir/contrib/pzstd/Makefile
    # -pzstd$(EXT): main.o $(PROGDIR)/util.o Options.o Pzstd.o SkippableFrame.o $(ZSTDDIR)/libzstd.a
    # -	$(LD_COMMAND)
    # +pzstd$(EXT): main.o $(PROGDIR)/util.o Options.o Pzstd.o SkippableFrame.o
    # +	$(LD_COMMAND) -L ../../lib -lzstd
    if pkg_create_orig "$f1"; then
        sed -i -r -e 's,^(.*) [^ ]+libzstd\.a$,\1,' "$f1"
        sed -i -r -e 's,^([ \t]*\$\(LD_COMMAND\))$,\1 -L ../../lib -lzstd,' "$f1"
    fi
    "${Make[@]}" "${MakeEnv[@]}" -C "$OrigSrcDir"/contrib/pzstd
}

pkg_post_install() {
    # Slackware
    pkg_install_mfd 755 "$OrigSrcDir"/contrib/pzstd/pzstd "$Prefix2/bin" || return 1
    pkg_install_mff 644 "$OrigSrcDir"/contrib/pzstd/README.md "$DocDir2"/README.pzstd.md
    # It might be advisable to have the libraries in /lib${LIBDIRSUFFIX}:
    ls -d "$LibDir2"/*.so.* | pkg_mv_ln "$DestDir/$LibName"
    # Symlink the static library or CMake gets mad:
    ls -d "$LibDir2"/libzstd.a | pkg_ln_d "$DestDir/$LibName"
    # Set the path of libzstd in cmake Targets (given by Steven Voges in SBo)
    sed -i 's|${_IMPORT_PREFIX}||g' "$LibDir2"/cmake/zstd/zstdTargets-release.cmake
}
