#!/bin/bash

PkgHome="https://github.com/tpm2-software/${Name,,}/tags"

check_VERSION() {
    local file=VERSION
    if [[ ! -f $file ]]; then
        echo "$Version" >"$file"
    fi
}

check_bootstrap() {
    local file=bootstrap
    if [[ -x $file ]]; then
        # git describe --tags --always --dirty > VERSION
        # --> #git ...
        sed -i -e 's,^git ,#git ,' "$file"

        ./bootstrap
    fi
}
