#!/bin/bash

PkgHome[1]="https://gitlab.xiph.org/xiph/theora/-/tags"
PkgHome[2]="https://github.com/xiph/theora/tags"

ConfigureOpts+=(
    --disable-examples
    --disable-spec
)

pkg_post_install() {
    rm -rf "$DocDir2"/{html,latex,*.stamp}
    :
}
