#!/bin/bash

ConfigureOpts+=(
    -Dshout2=disabled
)
[[ ! $PULSE ]] && ConfigureOpts+=(-Dpulse=disabled)
[[ ! $AALIB ]] &&
    ConfigureOpts+=(
        -Daalib=disabled # auto, aalib text console video sink plugin
        -Dlibcaca=disabled # auto, libcaca text console video sink plugin
    )
:
