#!/bin/bash

# REQ: openexr-2

ConfigureOpts+=(
    # Slackware
    -Ddvbsuboverlay=disabled
    -Ddvdspu=disabled
    -Dsiren=disabled
    -Dclosedcaption=disabled

    -Dneon=disabled
    -Dexamples=disabled
    -Dfaac=disabled
    -Dfaad=disabled
    -Dvoaacenc=disabled
    -Dvoamrwbenc=disabled
    -Dmodplug=disabled      # ModPlug audio decoder plugin (libmodplug)
)
[[ ! $IEEE1394 ]] && ConfigureOpts+=(-Ddc1394=disabled)
#[[ ! $RTMP ]] && ConfigureOpts+=(-Drtmp=disabled -Drtmp2=disabled)
:
