#!/bin/bash

pkg_set_python python3

ConfigureOpts+=(
    -Dpython=python3
)

ConfigureOpts+=(
    # Slackware
    -Dgtk_doc=false
)

pkg_pre_configure() {
    local f="tools/meson.build"
    # python3 --> python3.10
    # python_cmd = '/usr/bin/env python@0@'.format(python.language_version().split('.')[0])
    #   -.split('.')[0]
    if pkg_create_orig "$f"; then
        sed -i -e 's,\(python_cmd =.*\)\.split.*),\1),' "$f"
    fi
}

pkg_post_install() {
    "$Python" -m compileall "$LibDir2" -d /
}
