#!/bin/bash

if (($(pkg_cmp_versions "$Version" "1.80.2") < 0)); then
    BuildSteps=("python3.11") # distutils
else
    BuildSteps=("python3") # distutils
fi
[[ $BuildStep ]] && ConfigureOpts+=("-Dpython=$BuildStep")

ConfigureOpts+=(
    # Slackware
    -Dgtk_doc=false
)

pkg_pre_configure() {
    local f="tools/meson.build"
    # python3 --> python3.10
    # python_cmd = '/usr/bin/env python@0@'.format(python.language_version().split('.')[0])
    #   -.split('.')[0]
    if pkg_create_orig "$f"; then
        sed -i -e 's,\(python_cmd =.*\)\.split.*),\1),' "$f"
    fi
}

pkg_post_install() {
    pkg_python_compileall "$LibDir2"
}
