#!/bin/bash

PkgHome="https://download.samba.org/pub/?C=M;O=D"

BuildSteps=("${BuildForPython[@]}")
[[ $BuildStep ]] && pkg_set_python "$BuildStep"

# Make sure we get stable hashes
export PYTHONHASHSEED=1

pkg_post_install() {
    pkg_python_compileall "$DestDir"
}
