#!/bin/bash

ConfigureOpts+=(
    # Slackware
    -Dbuild-tests=false
    -Dupdate-mimedb=false # false, Call update-mime-database after install. It should not be enabled if DESTDIR is used
)

pkg_pre_make() {
    # Slackware
    # Don't use fdatasync() unless you want it to take 1000x longer
    # to update the mime database.  Seriously.
    local f1=src/config.h
    pkg_create_orig "$f1"
    sed -e "/HAVE_FDATASYNC/ d" -i "$f1"
}

pkg_post_install() {
    # Slackware
    # pkgconfig -> /usr/lib64/
    ls -d "$ShareDir2"/pkgconfig | pkg_mv_d "$LibDir2"
    # /var/log/setup/setup.07.update-mime-database
    pkg_install_mff 755 "$DestDir"/var/log/setup/setup.07.update-mime-database <<EOF
#BLURB="Run update-mime-database."
chroot . /usr/bin/update-mime-database /usr/share/mime 1>/dev/null 2>/dev/null
EOF
}

pkg_read2var pkg_post_installpkg <<EOF
pkg_post_installpkg() {
    # Slackware
    local update=/usr/bin/update-mime-database
    if [[ -x \$update ]]; then
        # \$update /usr/share/mime 1>/dev/null 2>/dev/null
        local passwdline homedir username dir
        cat /etc/passwd | while read passwdline ; do
            homedir=\$(echo \$passwdline | cut -f 6 -d :)
            dir=\$homedir/.local/share/mime
            if [[ -d \$dir ]]; then
                username=\$(echo \$passwdline | cut -f 1 -d :)
                # Sorry about the long command line, alienBOB  ;-)
                su \$username -c "\$update \$dir 1>/dev/null 2>/dev/null" 2>/dev/null
            fi
        done
        # This is just "cleanup" in case something might be missed in /home/*/
        local homemimedir
        for homemimedir in /home/*/.local/share/mime ; do
            if [[ -d \$homemimedir ]]; then
                username=\$(echo \$homemimedir | cut -f 3 -d /)
                su \$username -c "\$update \$homemimedir 1>/dev/null 2>/dev/null" 2>/dev/null
            fi
        done
    fi
}
pkg_post_installpkg
EOF
