#!/bin/bash

PkgHome+=(
    "https://github.com/libcdio/libcdio/tags"
)

ConfigureOpts+=(
    # Slackware
    --disable-silent-rules

    # non Slackware
    --enable-maintainer-mode # man files *.1
    --enable-vcd-info=no
)
