#!/bin/bash

ConfigureOpts+=(
    # Slackware
    --enable-device-mapper # enable device mapper support default=yes
    --with-readline # support fancy command line editing

    --disable-nls # do not use Native Language Support
)

pkg_pre_configure() {
    # Slackware
    pkg_add_cflags "-fgnu89-inline"

    # pkg_autoreconf
}
