#!/bin/bash

PkgHome[1]="https://packages.debian.org/bookworm/gnu-which"

ConfigureOpts+=(
    --bindir=/bin
)

pkg_post_install() {
    # Slackware
    ls -d "$DestDir"/bin/which | pkg_ln_d "$Prefix2/bin"
}
