#!/bin/bash

PkgHome=(
    "https://mkvtoolnix.download/source.html"
    # "https://gitlab.com/mbunkus/mkvtoolnix"
    "https://mkvtoolnix.download/sources/"
)

ConfigureOpts+=(
    --enable-gui=no
)
