#!/bin/bash

ConfigureOpts+=(
    --with-appdefaultdir="$Etc/X11/app-defaults"
)
[[ $PAM ]] && ConfigureOpts+=(--with-pam)

unset ProtectDirs

pkg_post_install() {
    # /usr/lib64/X11/xdm --> /etc/X11/xdm
    echo "$LibDir2/X11/xdm" | pkg_mv_ln "$Etc2/X11" || return 1

    # etc/X11: *.new
    local f
    while IFS= read -r f; do
        case "$f" in
            *.so|*.la|*.xpm|*/chooser|*.new)
                continue
                ;;
        esac
        mv "$f" "$f.new"
        pkg_doinst_add_config "$f"
    done < <(find "$DestDir"/etc/X11 -type f)

    # /var/lib/xdm
    mkdir -pm 755 "$DestDir/var/lib/xdm"
}
