#!/bin/bash

ConfigureOpts+=(
    --with-xorg-conf-dir="$Etc"/X11/xorg.conf.d # Default xorg.conf.d directory, default=${prefix}/share/X11/xorg.conf.d
        # 10-evdev.conf
        # WARNING: potential conflict with 40-libinput.conf
)
