#!/bin/bash

PkgHome=(
    "https://github.com/ibmruntimes/semeru25-binaries/releases/"
    "https://developer.ibm.com/languages/java/semeru-runtimes/downloads/"
)

# libjvm.so preloadLibrary(/opt/ibm-semeru-open-jdk/lib/default/libj9vm29.so):
#   /opt/ibm-semeru-open-jdk/lib/default/libj9vm29.so:
#   cannot enable executable stack as shared object requires: Invalid argument
# libjvm.so failed to load: j9vm29
