#!/bin/bash

ConfigureOpts+=(
    --enable-languages=cl # enable only specific language bindings: cl
    --with-libgpg-error-prefix="$Prefix" # prefix where GPG Error is installed (optional)
    --with-libassuan-prefix="$Prefix" # prefix where LIBASSUAN is installed (optional)

    #--disable-gpg-test
)
pkg_check=1

pkg_post_install() {
    gzip -9 "$DocDir2"/ChangeLog*
}
