#!/bin/bash

ConfigureOpts+=(
    -Dwith_glx=yes # [yes, no, auto], =auto
)

[[ $WAYLAND ]] && ConfigureOpts+=(-Dwith_wayland=yes) ||
    ConfigureOpts+=(-Dwith_wayland=no)

pkg_post_install() {
    # Slackware
    # Add a default config file to reduce message verbosity:
    pkg_install_mfd 644 "$SupportDir"/libva.conf "$Etc2"
    # Fix a couple of mistakenly executable header files:
    chmod 644 "$IncludeDir2"/va/*.h
}
