#!/bin/bash

PkgHome="https://aws.amazon.com/corretto/"

unset pkg_make pkg_check

pkg_install() {
    local prefix=/opt/$Name
    local destdir=$DestDir$prefix
    pkg_cp_fd -l . "$destdir"

    # lib/libjvm.so --> java/jre/**/libjvm.so
    # there are two libjvm.so: client and server
    find "$destdir" -type f -name libjvm.so | grep -F server |
        pkg_ln_d "$LibDir2"

    # profile.d
    local dir=$Etc2/profile.d
    pkg_install_mff 644 "$dir/java.sh" <<EOF
#!/bin/sh
export JAVA_HOME="$prefix"
export MANPATH="\${MANPATH}:\${JAVA_HOME}/man"
export PATH="\${PATH}:\${JAVA_HOME}/bin"
EOF
    pkg_install_mff 644 "$dir/java.csh" <<EOF
#!/bin/csh
setenv JAVA_HOME "$prefix"
setenv MANPATH \${MANPATH}:\${JAVA_HOME}/man
setenv PATH \${PATH}:\${JAVA_HOME}/bin
EOF

    # /usr/bin/java --> /usr/lib/java/bin/java
    ls "$destdir/bin"/{java,javac} | pkg_ln_d "$Prefix2/bin"
}
