#!/bin/bash

PkgHome="https://github.com/OpenPrinting/cups-filters/tags"

ConfigureOpts+=(
    # Slackware
    --runstatedir=/run
    # We "--disable-avahi" because this package can't even use it.
    --disable-avahi
    --disable-mutool
    --with-browseremoteprotocols=cups

    # --with-cups-config=cups-config
    # --enable-poppler # enable Poppler-based filters
    # --disable-ghostscript # Disable filters using Ghostscript
)

pkg_pre_configure() {
    # Slackware
    # GCC15 workaround:
    # pkg_add_cflags -Wno-error=incompatible-pointer-types -std=gnu17
    :
}
