#!/bin/bash

PkgHome="https://dbus.freedesktop.org/doc/dbus-glib/"

# dbus-glib is a deprecated API for use of D-Bus from GLib applications. Do not use it in new code.
# Since version 2.26, GLib's accompanying GIO library provides a high-level API for D-Bus,
# "GDBus", based on an independent reimplementation of the D-Bus protocol.
# The maintainers of D-Bus recommend that GLib applications should use GDBus instead of dbus-glib.

pkg_post_install() {
    # Slackware
    # Put bash-completion file in system directory:
    chmod 644 "$Etc2"/bash_completion.d/*.sh
    pkg_mv_ff "$Etc2"/bash_completion.d/*.sh "$ShareDir2"/bash-completion/completions/dbus
    find "$Etc2" -depth -type d -empty -delete
}
