#!/bin/bash

PkgHome=(
    "https://github.com/rockowitz/ddcutil/tags"
    "https://xaselgio.net/posts/08.playing-with-brightness/"
)

# unset ProtectDirs

MakeEnv=(
    # Slackware
    # Put the udev rules in the right place:
    rulesdir=/lib/udev/rules.d

    # installed_modulesdir=/etc/modules-load.d
)
InstallEnv+=("${MakeEnv[@]}")
