#!/bin/bash

PkgHome="https://github.com/derf/feh/tags"

# REQ: imlib2

MakeEnv=(
    PREFIX="$Prefix"
    exif=1
    magic=1
)
InstallEnv+=(
    "${MakeEnv[@]}"
    man_dir="$ManDir2"
    doc_dir="$DocDir2"
    example_dir="$DocDir2"/examples
)
