#!/bin/bash

PkgHome="https://github.com/ncroxon/gnu-efi/tags"

MakeEnv=(
    # Slackware
    #CPPFLAGS="$CFLAGS"
    LIBDIR="$LibDir"
    PKGCONFIGDIR="$LibDir"/pkgconfig

    PREFIX="$Prefix"
        # Slackware
        # sed -i "s,/usr/local,/usr,g" Make.defaults
)
InstallEnv+=(
    INSTALLROOT="$DestDir"
    "${MakeEnv[@]}"
)
CleanOpts=(clean)

pkg_post_install() {
    # Slackware
    # Fix install locations:
    mv "$LibDir2"/{*.lds,crt0*.o} "$LibDir2"/gnuefi/

    rm -f "$LibDir2"/gnu-efi.pc
    :
}
