#!/bin/bash

PkgHome=(
    "https://github.com/ncroxon/gnu-efi/tags"
    "$SlackwareMirrorUrl/l/gnu-efi/?C=M&O=D"
)

MakeEnv=(
    # Slackware
    #CPPFLAGS="$CFLAGS"
    LIBDIR="$LibDir"
    PKGCONFIGDIR="$LibDir"/pkgconfig

    PREFIX="$Prefix"
)
InstallEnv+=(
    # Slackware
    "${MakeEnv[@]}"

    INSTALLROOT="$DestDir"
)
CleanOpts=(clean)

pkg_post_install() {
    # Slackware
    # Fix install locations:
    mv "$LibDir2"/{*.lds,crt0*.o} "$LibDir2"/gnuefi/
}
