#!/bin/bash

PkgHome="https://gitlab.com/gnutls/gnutls/"

# REQ: nettle-3.x

ConfigureOpts+=(
    # Slackware
    --disable-rpath
    --with-included-libtasn1
    --with-brotli
    --with-idn
    --with-zstd
    --enable-openssl-compatibility

    --disable-doc
    --enable-libdane=no
    --without-tpm # Disable TPM (trousers) support
    --with-tpm2=yes # yes/link/dlopen/no, customize/disable TPM2 support
    --enable-ssl3-support # enable support for the SSL 3.0 protocol
)
MakeEnv+=(
    imagesdir="$DocDir"
)
InstallEnv+=("${MakeEnv[@]}")

pkg_pre_install() {
    sed -i -e 's,ginstall -c,ginstall -C,' doc/manpages/Makefile
}
