#!/bin/bash

ConfigureOpts+=(
    --bindir=/bin
)
pkg_check=1

pkg_post_install() {
    # Slackware
    # Replace the fgrep/egrep scripts with less annoying versions:
    # egrep, fgrep
    pkg_install_mff 755 "$DestDir"/bin/egrep <<EOF
#!/bin/sh
exec grep -E "\$@"
EOF
    pkg_install_mff 755 "$DestDir"/bin/fgrep <<EOF
#!/bin/sh
exec grep -F "\$@"
EOF
    # Make symlinks in /usr/bin:
    ls -d "$DestDir"/bin/* | pkg_ln_d "$Prefix2"/bin
}
