#!/bin/bash

PkgHome=(
    "https://sourceforge.net/projects/lame/files/lame/"
    "${DebianSearchURL}lame"
)

# v3.101
# id3tag.c:661:48: error:
# passing argument 4 of 'id3v2_add_utf8_lng' from incompatible pointer type [-Wincompatible-pointer-types]

ConfigureOpts+=(
    # Slackware
    --htmldir="$DocDir"/html
    --enable-mp3rtp
    --enable-nasm
)
MakeEnv=(
    pkgdocdir="$DocDir"
)
InstallEnv+=("${MakeEnv[@]}")

pkg_post_install() {
    # gzip -9 "$DocDir2"/ChangeLog

    # del old ChangeLog
    # <= 2021-03-09 10:52
    rm -f "$DocDir2"/ChangeLog
}
