#!/bin/bash

PkgHome=(
    "https://sourceforge.net/projects/lame/files/lame/"
    "${DebianSearchURL}lame"
)

ConfigureOpts+=(
    # Slackware
    --htmldir="$DocDir"/html
    --enable-mp3rtp
    --enable-nasm
)
MakeEnv=(
    pkgdocdir="$DocDir"
)
InstallEnv+=("${MakeEnv[@]}")

pkg_post_install() {
    # del old ChangeLog
    # <= 2021-03-09 10:52
    rm -f "$DocDir2"/ChangeLog
}
