#!/bin/bash

PkgHome=(
    # "https://pwhois.org/lft/index.who"
    "https://pwhois.org/get/"
)

pkg_read2var pkg_post_installpkg <<EOF
pkg_post_installpkg() {
    setcap 'cap_net_raw,cap_net_admin=eip' usr/bin/lft
}
pkg_post_installpkg
EOF
