#!/bin/bash

PkgHome="https://github.com/storaged-project/libblockdev"

pkg_set_python python3

ConfigureOpts+=(
    # Slackware
    #--without-dm
    #--without-python2
    #--with-python3 # support python3 [default=check]

    --enable-introspection=yes # no/auto/yes, Enable introspection for this build
    --enable-tests=no # Run tests at compile time (default=yes)
    #--with-dmraid=no # support dmraid [default=yes]
)

pkg_post_install() {
    pkg_python_compileall "$LibDir2"
}
