#!/bin/bash

PkgHome="https://github.com/libpwquality/libpwquality/tags"

BuildSteps=("${BuildForPython[@]}")
[[ $BuildStep ]] && pkg_set_python "$BuildStep"

ConfigureOpts+=(
    # Slackware
    --with-python-binary="$Python"
    --with-securedir="/$LibName/security"
)

pkg_post_install() {
    # python
    (
        cd python || exit 1
        "$Python" -m pip install . -t "$PythonPlatLibDir2"
    )
}
