#!/bin/bash

PkgHome=(
    "https://sourceforge.net/projects/libpng/files/"
    "https://sourceforge.net/projects/libpng-apng/files/" # APNG patch
    "https://github.com/pnggroup/libpng/tags"
)


ConfigureOpts+=(--enable-static)

pkg_pre_configure() {
    # apng
    pkg_patch_f3 libpng-1.6.58-apng.patch.gz 1 || return 1
}

pkg_post_install() {
    # /usr/include/libpng
    local name=${Name,,}
    local dir=$IncludeDir2/$name
    if [[ ! -d $dir ]]; then
        local dir2
        while dir2=$(pkg_read_exist); do
            ln -sfnr "$dir2" "$dir" # libpng16 -> libpng
            break
        done < <(find "$IncludeDir2" -mindepth 1 -maxdepth 1 -type d -name "$name*")
    fi

    # pngcp
    if [[ -e pngcp ]]; then
        pkg_install_mfd 755 pngcp "$Prefix2/bin"
    fi
}
