#!/bin/bash

PkgHome="https://github.com/LibRaw/LibRaw/tags"

ConfigureOpts+=(
    # Slackware
    --enable-jasper
        # 22.1: configure: WARNING: unrecognized options: --enable-jasper
    --enable-lcms

    --enable-jpeg
    --disable-examples
)
