#!/bin/bash

PkgHome="https://github.com/webmproject/libwebp/tags"

pkg_set_python python3

ConfigureOpts+=(
    # Slackware
    --disable-silent-rules
    --enable-everything
    --enable-swap-16bit-csp
)

# Slackware
if [[ $Arch = "i686" ]]; then
    ConfigureOpts+=(
        --disable-avx2
        --disable-sse4.1
    )
fi

pkg_post_install() {
    pkg_reinstall_python swig
}
