#!/bin/bash

PkgHome="https://github.com/webmproject/libwebp/tags"

ConfigureOpts+=(
    # Slackware
    --disable-silent-rules
    --enable-everything
    --enable-swap-16bit-csp
)

# Slackware
if [[ $Arch = "i686" ]]; then
    ConfigureOpts+=(
        --disable-avx2
        --disable-sse4.1
    )
fi

pkg_post_install() {
    local p f1
    for p in "${BuildForPython[@]}"; do
        pkg_set_python "$p"

        # version="0.0",
        f1=$SrcDir/swig/setup.py
        sed -i -re 's|^( *)version=.*,$|\1version="'"$Version"'",|' "$f1"

        pkg_reinstall_python swig
    done
}
