#!/bin/bash

PkgHome="https://download.gnome.org/sources/$Name/?C=M&O=D"

[[ ! $BuildSteps ]] && BuildSteps=("${BuildForPython[@]}")
if [[ $BuildStep ]]; then
    pkg_set_python "$BuildStep"
    ConfigureOpts+=("--with-python=$Python")
fi

pkg_pre_configure() {
    pkg_autoreconf
}
