#!/bin/bash

PkgHome="https://www.nftables.org/"

ConfigureOpts+=(
    # Slackware
    --with-xtables
    #--disable-python
    --with-json
    --with-cli=readline

    #--with-python-bin="$Python"
    #--enable-python
)
unset ProtectDirs

pkg_post_install() {
    local p
    for p in "${BuildForPython[@]}"; do
        pkg_set_python "$p"
        pkg_reinstall_python py
    done
}
