#!/bin/bash

PkgHome=(
    "https://www.nongnu.org/oath-toolkit/"
    "https://download.savannah.nongnu.org/releases/oath-toolkit/?C=M&O=D"
)

ConfigureOpts+=(
    --disable-xmltest
)

if [[ $PAM ]]; then
    ConfigureOpts+=(
        --enable-pam
        --with-pam-dir="/$LibName/security"
    )
else
    ConfigureOpts+=(--disable-pam)
fi
