#!/bin/bash

ConfigureOpts+=(
    # Slackware
    --sysconfdir=/etc/openvpn
    --enable-lzo
    --enable-iproute2
)
[[ ! $PAM ]] && ConfigureOpts+=(--disable-plugin-auth-pam)

pkg_post_install() {
    local i
    for i in sample-keys sample-config-files sample-scripts; do
        pkg_cp_fd "sample/$i" "$DocDir2"
    done
}
