#!/bin/bash

SrcDir=$OrigSrcDir/src
MakeEnv=(
    PREFIX="$Prefix"
    LIB_PREFIX="$LibDir"
    DOC_PREFIX="$DocDir"
    MAN_PREFIX="$ManDir"
)
InstallEnv+=(
    PREFIX="$Prefix2"
    LIB_PREFIX="$LibDir2"
    DOC_PREFIX="$DocDir2"
    MAN_PREFIX="$ManDir2"
)
CleanOpt=clean

pkg_pre_configure() {
    # jsapi.c:96:35: error:
    # passing argument 5 of ‘TryArgumentFormatter’ from incompatible pointer type
    # [-Wincompatible-pointer-types]
    local f=Makefile
    if pkg_create_orig "$f"; then
        # SMCFLAGS = ... -Wno-incompatible-pointer-types
        sed -i -r -e 's,^(SMCFLAGS *=.*),\1 -Wno-incompatible-pointer-types,' "$f"
    fi
}
