#!/bin/bash

PkgHome="https://github.com/qemu/qemu"

# REQ: libfdt (dtc), kernel (+IO_URING)

UseBuildDir=1
Configure=$OrigSrcDir/configure

pkg_configure_del --infodir --build --host
pkg_configure_del2 shared static

ConfigureOpts+=(
    # Slackware
    --enable-gtk
    --enable-kvm
    --enable-linux-io-uring
    --enable-malloc=jemalloc
    --enable-nettle
    --enable-sdl
    --enable-system
    --enable-vde
    --enable-virtfs
    --enable-vnc
    --enable-vnc-jpeg
    --enable-vnc-sasl
    --enable-spice-protocol
    --enable-spice
    --enable-slirp
    --enable-usb-redir
    --enable-vnc --enable-vnc-sasl --enable-vnc-jpeg

    --disable-docs
    --enable-crypto-afalg
    --enable-membarrier
    #--enable-modules
    --enable-virglrenderer
    --enable-vte
)

arr2list() {
    # (1 2 3) -> "1,2,3"
    local -n var_=$1
    local s i
    for i in "${var_[@]}"; do
        s+=",$i"
    done
    [[ $s ]] && s=${s:1} # del first ,
    echo "$s"
}

# Slackware
case $Arch in
    i686)
        kvm_arch="i386"
        # Sorry, but x86_64-softmmu, x86_64-linux-user, aarch64-softmmu, and
        # aarch64-linux-user do not work on x86:
        target=(
            arm-linux-user
            arm-softmmu
            armeb-linux-user
            i386-linux-user
            i386-softmmu
            sparc-linux-user
            sparc-softmmu
        )
        ;;
    x86_64)
        kvm_arch="x86_64"
        target=(
            aarch64-linux-user
            aarch64-softmmu
            arm-linux-user
            arm-softmmu
            armeb-linux-user
            i386-linux-user
            i386-softmmu
            sparc-linux-user
            sparc-softmmu
            sparc64-linux-user
            sparc64-softmmu
            x86_64-linux-user
            x86_64-softmmu
        )
        ;;
    *)
        kvm_arch=""
        target=(
            aarch64-linux-user
            aarch64-softmmu
            arm-linux-user
            arm-softmmu
            armeb-linux-user
            i386-linux-user
            i386-softmmu
            sparc-linux-user
            sparc-softmmu
            sparc64-linux-user
            sparc64-softmmu
            x86_64-linux-user
            x86_64-softmmu
        )
        ;;
esac
ConfigureOpts+=(--target-list="$(arr2list target)")

audio_drv_list=(
    alsa
    oss
    sdl
)
# alsa/coreaudio/default/dsound/jack/oss/pa/pipewire/sdl/sndio
[[ $JACK ]] && audio_drv_list+=(jack) ||
    ConfigureOpts+=(-Djack=disabled) # auto, JACK sound support
[[ $PULSE ]] && audio_drv_list+=(pa) || ConfigureOpts+=(--disable-pa)
[[ $PIPEWIRE ]] && audio_drv_list+=(pipewire)
ConfigureOpts+=(
    --audio-drv-list="$(arr2list audio_drv_list)"
)

pkg_post_install() {
    # Slackware
    ## Install udev rules for /dev/kvm:
    #local dir=$DestDir/lib/udev/rules.d
    #pkg_install_mfd 644 "$SupportDir"/65-kvm.rules "$dir"
    # Create "qemu-kvm" symlink. some 3rd party frontends look for it:
    [[ $kvm_arch ]] && ln -s qemu-system-"$kvm_arch" "$Prefix2"/bin/qemu-kvm
    :
}
