#!/bin/bash

# written in haskell
# shellcheck-0.11.0.linux.x86_64.tar.xz

unset pkg_configure pkg_make

pkg_install() {
    pkg_install_mfd 755 "$Name" "$Prefix2/bin" || return 1
    pkg_install_mfd 644 *.txt "$DocDir2"
}
