#!/bin/bash

PkgHome="https://repo.or.cz/socat.git"

ConfigureOpts+=(
    # Slackware
    # GNU readline support must be disabled since it is a GPL violation to also
    # link with OpenSSL, which is arguably more important here. It would be nice
    # to see editline support for this someday... or readline LGPLed.
    --disable-readline
)
pkg_check=

pkg_install() {
    # avoid yodl2man

    local i

    # Slackware
    # socat -> socat1
    pkg_install_mff 755 socat "$Prefix2"/bin/socat1 || return 1
    ln -sfn socat1 "$Prefix2"/bin/socat
    pkg_install_mff 755 doc/socat.1 "$ManDir2"/man1/socat1.1
    ln -sfn socat1.1 "$ManDir2"/man1/socat.1

    # Slackware
    # socat-chain.sh socat-mux.sh socat-broker.sh
    for i in socat-chain.sh socat-mux.sh socat-broker.sh; do
        [[ -f $i ]] && pkg_install_mfd 755 "$i" "$Prefix2"/bin
    done

    # procan filan
    pkg_install_mfd 755 procan filan "$Prefix2"/bin || return 1
}
