#!/bin/bash

PkgHome="https://github.com/sqlite/sqlite/tags"

pkg_configure_del --docdir --localedir

tclsh=$(readlink -f "$(command -v tclsh)")

tcl=$(sed -e 's,^tclsh,tcl,' <<<"${tclsh##*/}") # tcl8.6
tcllibdir=$LibDir/$tcl/sqlite3
tcllibdir2=$DestDir$tcllibdir

ConfigureOpts+=(
    # Slackware
    --enable-threadsafe
    --with-tempstore=yes
    --enable-load-extension
    --enable-fts3
    --enable-fts4
    --enable-fts5
    --enable-rtree
    --enable-session
    --with-tclsh="$tclsh"
    --soname=legacy # SONAME for libsqlite3.so.
        # "none", or not using this flag, sets no soname.
        # "legacy" sets it to its historical value of libsqlite3.so.0.
        # A value matching the glob "libsqlite3.*" sets it to that literal value.
        # Any other value is assumed to be a suffix which gets applied to "libsqlite3.so.",
        #   e.g. --soname=9.10 equates to "libsqlite3.so.9.10".

    --enable-readline
)

MakeOpts+=(
    # Slackware
    # Build extra tools:
    dbdump dbhash dbtotxt index_usage showdb showjournal
    showshm showstat4 showwal sqldiff sqlite3_analyzer
    sqlite3_expert sqlite3_rsync sqltclsh
)

pkg_pre_configure() {
    # Slackware
    # Define C preprocessor feature switches
    # https://www.sqlite.org/compile.html
    # Enable AND, NOT and nested parenthesis in FTS3
    pkg_add_cflags "-DSQLITE_ENABLE_FTS3_PARENTHESIS=1"
    # Enable the ICU extension
    pkg_add_cflags "-DSQLITE_ENABLE_ICU"
    # Enables the retrieval of column metadata
    pkg_add_cflags "-DSQLITE_ENABLE_COLUMN_METADATA=1"
    # Disable directory syncs
    pkg_add_cflags "-DSQLITE_DISABLE_DIRSYNC=1"
    # Add additional logic to the ANALYZE command and to the query planner
    # to chose better query plans under certain situations
    pkg_add_cflags "-DSQLITE_ENABLE_STAT4=1"
    # Enable the sqlite3_unlock_notify() interface and its associated functionality
    # https://www.sqlite.org/unlock_notify.html
    pkg_add_cflags "-DSQLITE_ENABLE_UNLOCK_NOTIFY=1"
    # The secure_delete setting causes deleted content to be overwritten with zeros
    # https://www.sqlite.org/pragma.html#pragma_secure_delete
    pkg_add_cflags "-DSQLITE_SECURE_DELETE=1"
    # Enable the "Resumable Bulk Update" extension
    # https://www.sqlite.org/rbu.html
    pkg_add_cflags "-DSQLITE_ENABLE_RBU=1"
    # Enable the DBSTAT Virtual Table
    # https://www.sqlite.org/dbstat.html
    # fossil: Error: system SQLite library omits required build option -DSQLITE_ENABLE_DBSTAT_VTAB
    pkg_add_cflags "-DSQLITE_ENABLE_DBSTAT_VTAB=1"
    ## Fix a bug in ./configure that discards all but the last considered option:
    #sed -i "s|\$(OPT_FEATURE_FLAGS)|\${OPT_FEATURE_FLAGS}|g" ./configure
    export CPPFLAGS="$CFLAGS $(icu-config --cppflags)"
    export LDFLAGS="$(icu-config --ldflags)"
    # We'll need this further down to clean up since we won't be including
    # the TCL library in this package.
    export TCLLIBDIR=$tcllibdir
}

pkg_post_install() {
    # Slackware
    # Install extra tools:
    local files=(
        dbdump dbhash dbtotxt index_usage showdb
        showjournal showshm showstat4 showwal sqldiff sqlite3_expert
        sqlite3_rsync
    )
    pkg_install_mfd 755 "${files[@]}" "$Prefix2"/bin
    # Don't ship the TCL stuff. Now that we have our soname back, the
    # stuff bundled with TCL should work again:
    rm -rf "$tcllibdir2"
    # Add missed man page:
    pkg_install_mfd 644 *.1 "$ManDir2"/man1
    # Fix up the pkgconfig file
    # sed -i 's|Libs: -L${libdir} -lsqlite3|Libs: -L${libdir} -lsqlite3 -ldl|g' \
    #     $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/sqlite3.pc
    sed -i -re 's|^(Libs:) (.*)|\1 \2 -ldl|g' "$LibDir2"/pkgconfig/sqlite3.pc

    # del empty dirs
    find "$LibDir2" -depth -type d -empty -delete
}
