#!/bin/bash

if [[ -d $OrigSrcDir/$Name ]]; then
    SrcDir=$OrigSrcDir/$Name
fi

MakeEnv=(
    # Slackware
    GZIP_SUPPORT=1
    XZ_SUPPORT=1
    LZ4_SUPPORT=1
    LZO_SUPPORT=1
    LZMA_XZ_SUPPORT=1
    ZSTD_SUPPORT=1
    COMP_DEFAULT=xz
)
InstallEnv=(
    # Slackware
    INSTALL_DIR="$Prefix2"/bin
    INSTALL_MANPAGES_DIR="$ManDir2"/man1
)

pkg_pre_configure() {
    # help2man: can't get `--help' info from /tmp/tmp.PQPfpKRfBy/mksquashfs.sh
    mkdir -p "_tmp"
    export TMPDIR=$(pwd)/_tmp
}
