#!/bin/bash

PkgHome="https://github.com/OpenPrinting/system-config-printer/tags"

BuildSteps=("${BuildForPython[@]}")
[[ $BuildStep ]] && pkg_set_python "$BuildStep"

unset ProtectDirs

ConfigureOpts+=(
    # Slackware
    --with-udevdir=/lib/udev
    --with-udev-rules
    --with-systemdsystemunitdir=no
    #--program-prefix=
    #--program-suffix=
)

MakeEnv=(
    dbusdir="$ShareDir/dbus-1/system.d"
)
InstallEnv+=("${MakeEnv[@]}")

pkg_post_install() {
    # reinstall python
    rm -rf "$PythonPureLibDir2"
    "$Python" -m pip install . -t "$PythonPureLibDir2"

    # Slackware
    # Generate .pyc files
    local name=${Name,,}
    "$Python" -m compileall "$ShareDir2/$name" -d /
    "$Python" -O -m compileall "$ShareDir2/$name" -d /

    # /etc/xdg/autostart/* -> *.new
    find "$Etc2"/xdg -type f ! -name '*.new' -exec mv {} {}.new \;
}
