#!/bin/bash

PkgHome=(
    "https://www.tcpdump.org/"
    "$SlackwareMirrorUrl/n/tcpdump/?C=M&O=D"
)

ConfigureOpts+=(
    --disable-smb
    --with-system-libpcap
)

pkg_post_install() {
    (
        cd "$Prefix2/bin" || exit 1
        ls "$Name".* | pkg_ln_equals
    )
}
