#!/bin/bash

PkgHome=(
    "https://git.cgsecurity.org/cgit/testdisk/"
    "https://www.cgsecurity.org/wiki/TestDisk_Download"
)

ConfigureOpts+=(
    --disable-qt # enable use of qt (default is YES)
)
