#!/bin/bash

PkgHome=(
    "https://pagure.io/volume_key"
    "${DebianSearchURL}libvolume-key1"
)

BuildSteps=("${BuildForPython[@]}")
[[ $BuildStep ]] && pkg_set_python "$BuildStep"

ConfigureOpts+=(
    --with-python=no
    --with-python3
    --disable-nls # do not use Native Language Support
)

pkg_pre_configure() {
    export PYTHON3=$Python
    export PYTHON3_CONFIG=$Python-config
}
