#!/bin/bash

PkgHome="https://www.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/"

# REQ: inih, icu

cronDir=$ShareDir/xfsprogs

ConfigureOpts+=(
    # Slackware
    --libdir=/"$LibName"
    --libexecdir="$LibDir"
    --sbindir=/sbin
    --bindir="$Prefix"/sbin
    --enable-shared=yes
    --enable-gettext=yes

    --with-crond-dir="$cronDir"
)
pkg_check=
Make=(make)
InstallEnv=(
    # Slackware
    DIST_ROOT="$DestDir"

    PKG_USER=root
    PKG_GROUP=root
    CROND_DIR="$cronDir"
    PKG_DOC_DIR="$DocDir"
)
InstallOpts=(
    # Slackware
    install
    install-dev
)
unset ProtectDirs

pkg_pre_configure() {
    # Slackware
    # https://zhangboyi.gitlab.io/post/2020-09-14-resolve-dso-missing-from-command-line-error/
    export LDFLAGS="-Wl,--copy-dt-needed-entries"
}

pkg_post_install() {
    # Slackware
    # The install location for many binaries changed with the update to 3.1.1,
    # but it seems like the wrong place to put most of this stuff:
    find "$DestDir"/sbin -type f -name 'xfs_*' ! -name 'xfs_repair' |
        pkg_mv_d "$Prefix2"/sbin
    # Make /usr/lib/libhandle.so a symlink to /lib/libhandle.so.1:
    local dir=$DestDir/$LibName
    ln -sfnr "$dir"/libhandle.so "$LibDir2"/libhandle.so
    # Remove bogus files:
    rm -f "$dir"/*.so
    # Fix shared library perms:
    find "$DestDir/$LibName" -type f -name 'lib*.so.*' -exec chmod 755 {} \;
}
