#!/bin/bash

PkgHome="https://github.com/Cyan4973/xxHash/tags"

MakeEnv=(
    prefix="$Prefix"
    libdir="$LibDir"
    includedir="$IncludeDir"
    mandir="$ManDir"
)
InstallEnv+=("${MakeEnv[@]}")

pkg_post_install() {
    # Slackware
    # Don't package static library:
    find "$LibDir2" -type f -name '*.a' -delete
}
