#!/bin/bash

unset pkg_configure pkg_make

pkg_install() {
    if (($(pkg_cmp_versions "$Version" "1.2.14") < 0)); then
        pkg_patch_f3 11b028a9a01e47fc9b48e4a566803752011902e2.patch 1 || return 1
    fi
    pkg_cp_fd ucm ucm2 "$ShareDir2/alsa"
}
