#!/bin/bash

ConfigureOpts+=(
    # Slackware
    -Dintrospection=true
    -Dgtk4=true
    -Dgtk_doc=false # Build the reference documentation (requires gi-docgen)

    -Dsystemd=disabled # auto, Use systemd socket activation for server programs
)
