#!/bin/bash

ConfigureOpts+=(
    # Slackware
    -Dintrospection=true
    -Dgtk4=true
    -Dgtk_doc=false # Build the reference documentation (requires gi-docgen)

    -Dsystemd=disabled # auto, Use systemd socket activation for server programs
)

pkg_read2var pkg_post_installpkg <<EOF
pkg_post_installpkg() {
    local exe dir

    # Slackware
    exe=/usr/bin/update-mime-database
    if [[ -x \$exe ]]; then
        "\$exe" usr/share/mime &>/dev/null
    fi
    #exe=usr/bin/gtk-update-icon-cache
    #dir=usr/share/icons/hicolor
    #if [[ -e \$dir/icon-theme.cache ]]; then
    #    if [[ -x \$exe ]]; then
    #        chroot . /"\$exe" /"\$dir" &>/dev/null
    #    fi
    #fi
    #exe=/usr/bin/glib-compile-schemas
    #dir=usr/share/glib-2.0/schemas
    #if [[ -e \$dir ]]; then
    #    if [[ -x \$exe ]]; then
    #        "\$exe" \$dir &>/dev/null
    #    fi
    #fi
}
pkg_post_installpkg
EOF
