#!/bin/bash

BuildSteps=("${BuildForPython[@]}")
[[ $BuildStep ]] && pkg_set_python "$BuildStep"

pkg_pre_configure() {
    # python3 = import('python').find_installation('python3', modules: 'gi')
    local f1=meson.build
    sed -i -re "s|find_installation\\('(python[0-9.]+)'|find_installation('$BuildStep'|" "$f1"
}

pkg_post_install() {
    "$Python" -m compileall "$PythonLibDir2"
}
