#!/bin/bash

PkgHome[1]="https://download.gimp.org/gimp/?C=M&O=D"

# REQ: openexr-3.2.x, mypaint-brushes-2.x, gexiv2<0.15.0

ConfigureOpts+=(
    # Slackware
    --localstatedir=/var/lib
    -Dlua=false
    -Dgi-docgen=disabled
    -Dcheck-update=no
    -Dheadless-tests=disabled

    -Denable-default-bin=enabled # auto, Install unversioned symlinks pointing to versioned executables (on UNIX) or unversioned duplicates (on Windows)
)

pkg_pre_configure() {
    # gimp-data
    # [submodule "gimp-data"]
    #     path = gimp-data
    #     url = https://gitlab.gnome.org/GNOME/gimp-data.git
    #     branch = main
    #     shallow = true
    local d1=gimp-data
    if [[ -d $d1 ]] && pkg_dir_empty "$d1"; then
        git clone --depth 1 "https://gitlab.gnome.org/GNOME/gimp-data" "$d1" || return 1
    fi

    # Slackware
    # Allow a newer gexiv2:
    pkg_patch_f3 0001-build-macos-Do-not-require-gexiv2-0.14-on-homebrew.patch 1 || return 1
}
