#!/bin/bash

PkgHome[1]="https://download.gimp.org/gimp/?C=M&O=D"

# REQ: openexr-3.2.x, mypaint-brushes-2.x

ConfigureOpts+=(
    # Slackware
    --localstatedir=/var/lib
    -Dlua=true
    -Dgi-docgen=disabled
    -Dcheck-update=no
    -Dheadless-tests=disabled

    -Denable-default-bin=enabled # auto, Install unversioned symlinks pointing to versioned executables (on UNIX) or unversioned duplicates (on Windows)
)
