#!/bin/bash

ConfigureOpts+=(
    # Slackware
    -Dselinux=disabled
    -Dglib_debug=disabled
    -Dman-pages=enabled
    -Ddocumentation=false
    -Dinstalled_tests=false
)

pkg_post_install() {
    # Slackware
    # Install profile scripts:
    local i
    for i in libglib2.csh libglib2.sh; do
        pkg_install_mfd 755 "$SupportDir/$i" "$Etc2"/profile.d
    done
}

pkg_read2var pkg_post_installpkg <<EOF
pkg_post_installpkg() {
    # Slackware
    # Try to run these.  If they fail, no biggie.
    #chroot . /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/ &>/dev/null
    chroot . /usr/bin/gio-querymodules "$LibDir"/gio/modules/ &>/dev/null
}
pkg_post_installpkg
EOF
