#!/bin/bash

ConfigureOpts+=(
    #--enable-manual=no
    #--disable-celt051
    -Dtests=false # true, Build the test binaries
    #-Dgstreamer="1.0" # ['1.0', '0.10', 'no'], Enable gstreamer support
    #-Dsmartcard=enabled # Enable smartcard support
    -Dmanual=false # true, Build SPICE manual (asciidoc error)
)

pkg_pre_configure() {
    #[submodule "spice-common"]
    #	path = subprojects/spice-common
    #	url = ../spice-common.git
    local d1=subprojects/spice-common
    local url="https://gitlab.freedesktop.org/spice/spice-common"
    if pkg_dir_empty "$d1"; then
        git clone --depth 1 "$url" "$d1"
    fi

    # meson.build
    # version : run_command('build-aux/git-version-gen', meson.source_root() + '/.tarball-version', check : true).stdout().strip(),
    #   /usr/lib64/pkgconfig/spice-server.pc
    #   Version: UNKNOWN
    local f1=meson.build
    if pkg_create_orig "$f1"; then
        sed -i -re 's/^( *version :) run_command.*,$/\1 '"'$Version'"',/' "$f1"
    fi
}
