#!/bin/bash

PkgHome="https://github.com/intel/media-driver/tags"

# REQ: intel-gmmlib

ConfigureOpts+=(
    # Slackware
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5.0
    -DINSTALL_DRIVER_SYSCONF=OFF
    -DMEDIA_BUILD_FATAL_WARNINGS=OFF
    -Wno-dev
)

pkg_pre_configure() {
    # Slackware
    # [PATCH] Fix AVC decode resolution check for non-macroblock-aligned surfaces
    pkg_patch_f3 2.patch 1 || return 1

    # clang
    # media_softlet/linux/common/os/xe/mos_bufmgr_xe.c:1091:52: error:
    #   variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
    pkg_add_cflags "-Wno-error=vla-cxx-extension"
}
