#!/bin/bash

ConfigureOpts+=(
    # Slackware
    --with-xtables
    #--disable-python
    --with-json
    --with-cli=readline
)
unset ProtectDirs

pkg_post_install() {
    # python
    local p
    for p in "${BuildForPython[@]}"; do
        pkg_set_python "$p"
        (
            cd py || exit 1
            "$Python" -m pip install . -t "$PythonPureLibDir2"
        )
    done
}
