#!/bin/bash

BuildSteps=("${BuildForPython[@]}")
[[ $BuildStep ]] && pkg_set_python "$BuildStep"

ConfigureOpts+=(
    -DPYTHON=ON
    -DPython3_EXECUTABLE="$Python"
    -DBoost_PYTHON_VERSION="$PythonV12"
)
